namespace AccessTokenFromHttpContextTests;
public static class MockData
{
    public static string AccessTokenWithoutBearer = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkZha2VUb2tlblVzZXIiLCJpYXQiOjE1MTYyMzkwMjJ9.7bZnO9yGQgA9nD_2Y5LlHnEJaqVZPw6KxY8gAqWbZgw";
    public static string AccessTokenWithBearer = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkZha2VUb2tlblVzZXIiLCJpYXQiOjE1MTYyMzkwMjJ9.7bZnO9yGQgA9nD_2Y5LlHnEJaqVZPw6KxY8gAqWbZgw";

}
