global using CountFilesInaFolderLibrary.AdvancedApproach.UsingLINQWithDirectoryEnumerateFiles;
global using CountFilesInaFolderLibrary.AdvancedApproach.UsingWinAPI;
global using CountFilesInaFolderLibrary.BasicApproach;
global using System.Runtime.InteropServices;
global using Xunit;
