// <auto-generated />
using System;
using App;
using App.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(WebShopDbContext))]
    partial class WebShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("App.ClothingItem", b =>
                {
                    b.HasBaseType("App.Item");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("ClothingItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("674c9e27-4910-45fc-afd1-c4f0741fa33a"),
                            Description = "Nike Air Max",
                            Price = 8000m,
                            Color = "Black",
                            Material = "Leather",
                            Size = "M"
                        },
                        new
                        {
                            Id = new Guid("75867853-938b-43d9-a966-7813c21bcf76"),
                            Description = "Nike Air Max-2",
                            Price = 67275m,
                            Color = "Red",
                            Material = "Leather",
                            Size = "M"
                        });
                });

            modelBuilder.Entity("App.ElectronicItem", b =>
                {
                    b.HasBaseType("App.Item");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.ToTable("ElectronicItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d360dbc-22ce-467c-93ac-692079ca68c5"),
                            Description = "Samsung Galaxy S21",
                            Price = 8000m,
                            Manufacturer = "Samsung",
                            Model = "S21"
                        },
                        new
                        {
                            Id = new Guid("0672516e-15f5-4d46-a7e3-5fd024ec9505"),
                            Description = "Samsung Galaxy S20",
                            Price = 67275m,
                            Manufacturer = "Samsung",
                            Model = "S20"
                        },
                        new
                        {
                            Id = new Guid("f46ccdc0-f514-4834-af90-2484a8e81162"),
                            Description = "Samsung Galaxy S10",
                            Price = 600m,
                            Manufacturer = "Samsung",
                            Model = "S10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
