global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using ReadingAppsettingsInConsoleApplication.Configurations.ConfigurationProviders.Abstracts;
