// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp2
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"male")]
            public float Male { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"age")]
            public float Age { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"education")]
            public float Education { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"currentSmoker")]
            public float CurrentSmoker { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"cigsPerDay")]
            public float CigsPerDay { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"BPMeds")]
            public float BPMeds { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"prevalentStroke")]
            public float PrevalentStroke { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"prevalentHyp")]
            public float PrevalentHyp { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"diabetes")]
            public float Diabetes { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"totChol")]
            public float TotChol { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"sysBP")]
            public float SysBP { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"diaBP")]
            public float DiaBP { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"BMI")]
            public float BMI { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"heartRate")]
            public float HeartRate { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"glucose")]
            public float Glucose { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"TenYearCHD")]
            public float TenYearCHD { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"male")]
            public float Male { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"education")]
            public float Education { get; set; }

            [ColumnName(@"currentSmoker")]
            public float CurrentSmoker { get; set; }

            [ColumnName(@"cigsPerDay")]
            public float CigsPerDay { get; set; }

            [ColumnName(@"BPMeds")]
            public float BPMeds { get; set; }

            [ColumnName(@"prevalentStroke")]
            public float PrevalentStroke { get; set; }

            [ColumnName(@"prevalentHyp")]
            public float PrevalentHyp { get; set; }

            [ColumnName(@"diabetes")]
            public float Diabetes { get; set; }

            [ColumnName(@"totChol")]
            public float TotChol { get; set; }

            [ColumnName(@"sysBP")]
            public float SysBP { get; set; }

            [ColumnName(@"diaBP")]
            public float DiaBP { get; set; }

            [ColumnName(@"BMI")]
            public float BMI { get; set; }

            [ColumnName(@"heartRate")]
            public float HeartRate { get; set; }

            [ColumnName(@"glucose")]
            public float Glucose { get; set; }

            [ColumnName(@"TenYearCHD")]
            public uint TenYearCHD { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("TenYearCHD");
            if (labelColumn == null)
            {
                throw new Exception("TenYearCHD column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
