// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MLModel1_ConsoleApp2
{
    public partial class MLModel1
    {
        public const string RetrainFilePath =  @"C:\Users\ivanm\source\repos\tecmaivan\CodeMazeGuides\csharp-machine-learning\ML.NET_AutoML_API\AutoML_App\AutoML_App\DataSets\framingham.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader);
        }



        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }


        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"male", @"male"),new InputOutputColumnPair(@"age", @"age"),new InputOutputColumnPair(@"education", @"education"),new InputOutputColumnPair(@"currentSmoker", @"currentSmoker"),new InputOutputColumnPair(@"cigsPerDay", @"cigsPerDay"),new InputOutputColumnPair(@"BPMeds", @"BPMeds"),new InputOutputColumnPair(@"prevalentStroke", @"prevalentStroke"),new InputOutputColumnPair(@"prevalentHyp", @"prevalentHyp"),new InputOutputColumnPair(@"diabetes", @"diabetes"),new InputOutputColumnPair(@"totChol", @"totChol"),new InputOutputColumnPair(@"sysBP", @"sysBP"),new InputOutputColumnPair(@"diaBP", @"diaBP"),new InputOutputColumnPair(@"BMI", @"BMI"),new InputOutputColumnPair(@"heartRate", @"heartRate"),new InputOutputColumnPair(@"glucose", @"glucose")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"male",@"age",@"education",@"currentSmoker",@"cigsPerDay",@"BPMeds",@"prevalentStroke",@"prevalentHyp",@"diabetes",@"totChol",@"sysBP",@"diaBP",@"BMI",@"heartRate",@"glucose"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"TenYearCHD",inputColumnName:@"TenYearCHD",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=25,NumberOfLeaves=9,FeatureFraction=0.9096127F,LabelColumnName=@"TenYearCHD",FeatureColumnName=@"Features"}),labelColumnName:@"TenYearCHD"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
