
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp2;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Male = 0F,
    Age = 78F,
    Education = 2F,
    CurrentSmoker = 1F,
    CigsPerDay = 20F,
    BPMeds = 0F,
    PrevalentStroke = 0F,
    PrevalentHyp = 1F,
    Diabetes = 1F,
    TotChol = 250F,
    SysBP = 121F,
    DiaBP = 91F,
    BMI = 4873F,
    HeartRate = 195F,
    Glucose = 176F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual TenYearCHD with predicted TenYearCHD from sample data...\n\n");


Console.WriteLine($"Male: {0F}");
Console.WriteLine($"Age: {46F}");
Console.WriteLine($"Education: {2F}");
Console.WriteLine($"CurrentSmoker: {0F}");
Console.WriteLine($"CigsPerDay: {0F}");
Console.WriteLine($"BPMeds: {0F}");
Console.WriteLine($"PrevalentStroke: {0F}");
Console.WriteLine($"PrevalentHyp: {0F}");
Console.WriteLine($"Diabetes: {0F}");
Console.WriteLine($"TotChol: {250F}");
Console.WriteLine($"SysBP: {121F}");
Console.WriteLine($"DiaBP: {81F}");
Console.WriteLine($"BMI: {2873F}");
Console.WriteLine($"HeartRate: {95F}");
Console.WriteLine($"Glucose: {76F}");
Console.WriteLine($"TenYearCHD: {0F}");

var prediction = MLModel1.Predict(sampleData);
Console.WriteLine($"{prediction.PredictedLabel}");

var sortedScoresWithLabel = MLModel1.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

