// <auto-generated />
using System;
using BogusNugetPackage.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BogusNugetPackage.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20230107100959_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BogusNugetPackage.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personality")
                        .HasColumnType("int");

                    b.Property<int>("YearsOld")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fd6ae79-0aac-4348-b7a7-6b99d50e04e6"),
                            AboutMe = "Minima nostrum voluptas odit delectus molestiae saepe. Est exercitationem eligendi perspiciatis officia illo. Voluptatem quo rerum rerum sapiente numquam ut in pariatur nisi. Non officia consequatur asperiores quia eos culpa aspernatur dolores.",
                            Address = "02956 Jaunita Pike, New Erna, Argentina",
                            Email = "Jo_Kautzer46@yahoo.com",
                            FirstName = "Jo",
                            LastName = "Kautzer",
                            Personality = 1,
                            YearsOld = 44
                        },
                        new
                        {
                            Id = new Guid("20874be0-9d4a-4f5a-8234-67a8a481e8c3"),
                            AboutMe = "Odio quod voluptas quibusdam amet enim. Ipsam quas itaque unde.",
                            Address = "056 Abdullah Fork, Jasenfort, Norfolk Island",
                            Email = "Winnifred81@yahoo.com",
                            FirstName = "Winnifred",
                            LastName = "Hilpert",
                            Personality = 2,
                            YearsOld = 45
                        },
                        new
                        {
                            Id = new Guid("9e466cc5-6e87-4554-ac09-311770eea66f"),
                            AboutMe = "Dolore voluptas dolor dolore tenetur magnam veritatis ut voluptatibus. Est provident culpa dolor ut minima. Consequuntur vel officia. Pariatur et maiores quia cum qui aperiam dolorem.",
                            Address = "622 Cyril Freeway, Lake Lilliana, Denmark",
                            Email = "Jeramie.Strosin@hotmail.com",
                            FirstName = "Jeramie",
                            LastName = "Strosin",
                            Personality = 2,
                            YearsOld = 78
                        },
                        new
                        {
                            Id = new Guid("1c612c96-19d0-490e-adec-60e85260344e"),
                            AboutMe = "Repudiandae atque perferendis hic delectus ab accusamus delectus. Adipisci nihil voluptas distinctio et repellat dolor est et quo.",
                            Address = "85838 Torphy Cliff, South Ben, Martinique",
                            Email = "Brennan_Huel@yahoo.com",
                            FirstName = "Brennan",
                            LastName = "Huel",
                            Personality = 1,
                            YearsOld = 25
                        },
                        new
                        {
                            Id = new Guid("6ca12bcd-32a8-49a2-8968-2537adbffae6"),
                            AboutMe = "Est in odit minus et ducimus repudiandae sunt. Corrupti quidem quasi maxime molestias quidem.",
                            Address = "854 Hamill Forest, Willchester, Holy See (Vatican City State)",
                            Email = "Aileen_Thiel38@yahoo.com",
                            FirstName = "Aileen",
                            LastName = "Thiel",
                            Personality = 1,
                            YearsOld = 30
                        },
                        new
                        {
                            Id = new Guid("d53a07c9-f050-4433-bbda-72b8998e71c3"),
                            AboutMe = "Qui pariatur dolores. Tempore provident in possimus excepturi et aliquid facilis. Omnis quisquam quis quas ratione soluta sunt quia. Excepturi natus voluptatem iusto.",
                            Address = "268 Klocko Mills, North Krystina, Moldova",
                            Email = "Kim.Barrows14@hotmail.com",
                            FirstName = "Kim",
                            LastName = "Barrows",
                            Personality = 1,
                            YearsOld = 81
                        },
                        new
                        {
                            Id = new Guid("e3b6b04c-08a9-4e99-b789-90a6a38b4fb2"),
                            AboutMe = "Molestiae sequi ducimus ratione. Inventore quia sunt iure.",
                            Address = "387 Ubaldo Falls, New Mariettafurt, Saint Martin",
                            Email = "Waldo_Schultz47@hotmail.com",
                            FirstName = "Waldo",
                            LastName = "Schultz",
                            Personality = 0,
                            YearsOld = 61
                        },
                        new
                        {
                            Id = new Guid("4f0bc77c-9d5b-4f74-b669-a83bca677607"),
                            AboutMe = "Ea aut est nemo.",
                            Address = "6820 Amber Field, North Eulaliamouth, Palestinian Territory",
                            Email = "Griffin.Langworth@hotmail.com",
                            FirstName = "Griffin",
                            LastName = "Langworth",
                            Personality = 1,
                            YearsOld = 68
                        },
                        new
                        {
                            Id = new Guid("bf786d3a-63fe-4770-91e3-c3c039c6ba12"),
                            AboutMe = "Id vel non corrupti aut ut beatae.",
                            Address = "91971 Santina Rapids, Lake Jalentown, Slovenia",
                            Email = "Macie82@yahoo.com",
                            FirstName = "Macie",
                            LastName = "McClure",
                            Personality = 2,
                            YearsOld = 68
                        },
                        new
                        {
                            Id = new Guid("8efb3e7d-7085-4a45-8d42-440213e1c6ee"),
                            AboutMe = "Et repellat nihil recusandae non quibusdam accusantium.",
                            Address = "966 Felipe Vista, North Tialand, Azerbaijan",
                            Email = "Rory_Larkin96@gmail.com",
                            FirstName = "Rory",
                            LastName = "Larkin",
                            Personality = 1,
                            YearsOld = 31
                        });
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1b8080f-99de-4abe-b553-6573be598bd1"),
                            EmployeeId = new Guid("8fd6ae79-0aac-4348-b7a7-6b99d50e04e6"),
                            Fuel = "Gasoline",
                            Manufacturer = "Tesla"
                        },
                        new
                        {
                            Id = new Guid("2e216efb-43fe-47a9-bac8-3214a4c59e5a"),
                            EmployeeId = new Guid("8fd6ae79-0aac-4348-b7a7-6b99d50e04e6"),
                            Fuel = "Hybrid",
                            Manufacturer = "Hyundai"
                        },
                        new
                        {
                            Id = new Guid("65d71047-dff2-4157-b35f-69ce69256060"),
                            EmployeeId = new Guid("20874be0-9d4a-4f5a-8234-67a8a481e8c3"),
                            Fuel = "Gasoline",
                            Manufacturer = "Rolls Royce"
                        },
                        new
                        {
                            Id = new Guid("7ca5101f-1ecd-45dd-a4a4-1519b8bc0449"),
                            EmployeeId = new Guid("20874be0-9d4a-4f5a-8234-67a8a481e8c3"),
                            Fuel = "Diesel",
                            Manufacturer = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("c2318e06-896e-4702-a21e-985e5a853658"),
                            EmployeeId = new Guid("9e466cc5-6e87-4554-ac09-311770eea66f"),
                            Fuel = "Gasoline",
                            Manufacturer = "Ford"
                        },
                        new
                        {
                            Id = new Guid("9d271c7a-2a35-421d-ac5b-ee52f8c8a60a"),
                            EmployeeId = new Guid("9e466cc5-6e87-4554-ac09-311770eea66f"),
                            Fuel = "Diesel",
                            Manufacturer = "Mazda"
                        },
                        new
                        {
                            Id = new Guid("db85c546-072a-407c-a7cd-093d31d9bb0d"),
                            EmployeeId = new Guid("1c612c96-19d0-490e-adec-60e85260344e"),
                            Fuel = "Hybrid",
                            Manufacturer = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("d46b8ab8-b908-42c5-b95b-bd35bc9ad04f"),
                            EmployeeId = new Guid("1c612c96-19d0-490e-adec-60e85260344e"),
                            Fuel = "Gasoline",
                            Manufacturer = "Rolls Royce"
                        },
                        new
                        {
                            Id = new Guid("6c5b9c00-8c76-46c2-8323-24fe5d9452a8"),
                            EmployeeId = new Guid("6ca12bcd-32a8-49a2-8968-2537adbffae6"),
                            Fuel = "Electric",
                            Manufacturer = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("a4c71bdf-c213-473b-be69-6b6b8fed681b"),
                            EmployeeId = new Guid("6ca12bcd-32a8-49a2-8968-2537adbffae6"),
                            Fuel = "Hybrid",
                            Manufacturer = "Jaguar"
                        },
                        new
                        {
                            Id = new Guid("daf1929a-1efd-4e6e-a682-cb98dc4625c5"),
                            EmployeeId = new Guid("d53a07c9-f050-4433-bbda-72b8998e71c3"),
                            Fuel = "Diesel",
                            Manufacturer = "Cadillac"
                        },
                        new
                        {
                            Id = new Guid("b5ced04e-2cbc-4eef-b33b-c7e66d06e496"),
                            EmployeeId = new Guid("d53a07c9-f050-4433-bbda-72b8998e71c3"),
                            Fuel = "Diesel",
                            Manufacturer = "Jeep"
                        },
                        new
                        {
                            Id = new Guid("1d64485c-8345-4c01-ac32-34dc102d7d13"),
                            EmployeeId = new Guid("e3b6b04c-08a9-4e99-b789-90a6a38b4fb2"),
                            Fuel = "Electric",
                            Manufacturer = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("e1e3f5f0-61c0-43b2-b84d-30c1d4c2a2ec"),
                            EmployeeId = new Guid("e3b6b04c-08a9-4e99-b789-90a6a38b4fb2"),
                            Fuel = "Hybrid",
                            Manufacturer = "Tesla"
                        },
                        new
                        {
                            Id = new Guid("0cba016f-8cde-462b-bb60-0276ace7a5ff"),
                            EmployeeId = new Guid("4f0bc77c-9d5b-4f74-b669-a83bca677607"),
                            Fuel = "Electric",
                            Manufacturer = "Smart"
                        },
                        new
                        {
                            Id = new Guid("8f4f91f7-64bc-4076-b14a-514b7d0aa78a"),
                            EmployeeId = new Guid("4f0bc77c-9d5b-4f74-b669-a83bca677607"),
                            Fuel = "Electric",
                            Manufacturer = "Jeep"
                        },
                        new
                        {
                            Id = new Guid("0ae028f2-741b-405c-92af-ba8800753f55"),
                            EmployeeId = new Guid("bf786d3a-63fe-4770-91e3-c3c039c6ba12"),
                            Fuel = "Diesel",
                            Manufacturer = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("8e5e63d1-449a-4550-9371-0bde35b36b4c"),
                            EmployeeId = new Guid("bf786d3a-63fe-4770-91e3-c3c039c6ba12"),
                            Fuel = "Diesel",
                            Manufacturer = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("d6ca0659-814f-43ba-a32a-7a1af0aa5467"),
                            EmployeeId = new Guid("8efb3e7d-7085-4a45-8d42-440213e1c6ee"),
                            Fuel = "Electric",
                            Manufacturer = "Volvo"
                        },
                        new
                        {
                            Id = new Guid("e7614f08-a682-4557-8fff-98889ab39980"),
                            EmployeeId = new Guid("8efb3e7d-7085-4a45-8d42-440213e1c6ee"),
                            Fuel = "Diesel",
                            Manufacturer = "Bentley"
                        });
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Vehicle", b =>
                {
                    b.HasOne("BogusNugetPackage.Models.Employee", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Employee", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
