// <auto-generated />
using System;
using BogusNugetPackage.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BogusNugetPackage.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BogusNugetPackage.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personality")
                        .HasColumnType("int");

                    b.Property<int>("YearsOld")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("197f4bb5-04d3-41c8-9e6a-7d5e71003ee1"),
                            AboutMe = "Voluptatum eum animi. Voluptate sint enim esse optio. Excepturi asperiores dolorem. Nesciunt assumenda omnis repudiandae fugiat consequuntur et impedit.",
                            Address = "119 Efren Knolls, East Vicenta, United Kingdom",
                            Email = "Rashad95@gmail.com",
                            FirstName = "Rashad",
                            LastName = "McDermott",
                            Personality = 0,
                            YearsOld = 36
                        },
                        new
                        {
                            Id = new Guid("8abcd94b-490d-4e5e-9c6e-4caeefd89d8c"),
                            AboutMe = "Voluptas expedita dolor pariatur. Amet ea animi doloremque voluptatum consectetur quia dolorem ut explicabo.",
                            Address = "89201 Muller Village, Koeppview, Brunei Darussalam",
                            Email = "Joesph.Schoen78@hotmail.com",
                            FirstName = "Joesph",
                            LastName = "Schoen",
                            Personality = 1,
                            YearsOld = 52
                        },
                        new
                        {
                            Id = new Guid("a58e9c9e-45a2-489e-88d2-4554b585dce1"),
                            AboutMe = "Exercitationem consequatur hic. Quos possimus pariatur facilis illum non quis.",
                            Address = "9466 Abshire Wall, West Crawfordbury, Mozambique",
                            Email = "Clemmie_Nader10@yahoo.com",
                            FirstName = "Clemmie",
                            LastName = "Nader",
                            Personality = 0,
                            YearsOld = 84
                        },
                        new
                        {
                            Id = new Guid("01df40e2-a098-462b-a42f-50a88ae8927f"),
                            AboutMe = "Voluptatem distinctio exercitationem commodi excepturi inventore. Accusantium dolores consequuntur. Ipsa aut enim voluptatibus sint eos.",
                            Address = "231 Larkin Loaf, Daphneechester, Aruba",
                            Email = "Warren_Rodriguez24@hotmail.com",
                            FirstName = "Warren",
                            LastName = "Rodriguez",
                            Personality = 0,
                            YearsOld = 37
                        },
                        new
                        {
                            Id = new Guid("38886041-4440-4f44-9177-acb509de7610"),
                            AboutMe = "Aut odio libero aperiam. Sequi officiis autem molestiae excepturi repellat est molestiae harum et.",
                            Address = "20926 Katelin Centers, New Rileyport, Bangladesh",
                            Email = "Mittie30@hotmail.com",
                            FirstName = "Mittie",
                            LastName = "Greenfelder",
                            Personality = 1,
                            YearsOld = 60
                        },
                        new
                        {
                            Id = new Guid("b000ed0a-2921-4708-ad31-0cc0bd8766d6"),
                            AboutMe = "Qui et dolorum a. Sunt quos beatae ad consectetur laborum voluptatem quis possimus et.",
                            Address = "09720 Pattie Isle, Jaskolskifort, Vietnam",
                            Email = "Alessandra.Volkman49@gmail.com",
                            FirstName = "Alessandra",
                            LastName = "Volkman",
                            Personality = 0,
                            YearsOld = 79
                        },
                        new
                        {
                            Id = new Guid("1ce4c6f0-a08c-4bea-a7c6-0e5bbf43b6b8"),
                            AboutMe = "Sed enim soluta facere sequi corrupti temporibus possimus ex. Optio ad quis minima doloremque placeat et nam ipsa reiciendis.",
                            Address = "876 Kavon Mountain, New Fredericborough, Botswana",
                            Email = "Alvah58@hotmail.com",
                            FirstName = "Alvah",
                            LastName = "Dicki",
                            Personality = 1,
                            YearsOld = 27
                        },
                        new
                        {
                            Id = new Guid("8fc9af11-7c57-4967-a18e-eaee2b57dfe7"),
                            AboutMe = "Rerum voluptates voluptatibus impedit. Esse quod placeat earum. Minima enim laboriosam laborum. Illum ipsa animi aliquid.",
                            Address = "7877 Konopelski Village, Roweside, Somalia",
                            Email = "Alessandra.Murray@yahoo.com",
                            FirstName = "Alessandra",
                            LastName = "Murray",
                            Personality = 1,
                            YearsOld = 46
                        },
                        new
                        {
                            Id = new Guid("dca79394-4910-4111-aba5-6b780a16b537"),
                            AboutMe = "Ut asperiores fugiat rerum. Mollitia sapiente nostrum et enim excepturi optio. Dolorem expedita voluptas quia dolor rerum tempora cupiditate quas.",
                            Address = "2005 Maximo Drive, Baumbachshire, Republic of Korea",
                            Email = "Ross.Zemlak67@hotmail.com",
                            FirstName = "Ross",
                            LastName = "Zemlak",
                            Personality = 1,
                            YearsOld = 24
                        },
                        new
                        {
                            Id = new Guid("e45cae6a-9067-4de6-b623-a0a05252ef56"),
                            AboutMe = "Alias omnis aut quisquam aut eligendi et quae quae. Nostrum ab natus. Velit aut vel dicta esse nobis eos.",
                            Address = "982 McClure Cliffs, Lednerton, Czech Republic",
                            Email = "Raleigh_Fisher@hotmail.com",
                            FirstName = "Raleigh",
                            LastName = "Fisher",
                            Personality = 2,
                            YearsOld = 62
                        });
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f0a4d1d-2835-4fd6-9b16-11074068adf1"),
                            EmployeeId = new Guid("197f4bb5-04d3-41c8-9e6a-7d5e71003ee1"),
                            Fuel = "Hybrid",
                            Manufacturer = "Chevrolet"
                        },
                        new
                        {
                            Id = new Guid("9342ea97-0fe2-49cb-a473-f150d9f4542e"),
                            EmployeeId = new Guid("197f4bb5-04d3-41c8-9e6a-7d5e71003ee1"),
                            Fuel = "Electric",
                            Manufacturer = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("4f4bd1a7-1140-458f-92ad-bf635b4757a7"),
                            EmployeeId = new Guid("197f4bb5-04d3-41c8-9e6a-7d5e71003ee1"),
                            Fuel = "Gasoline",
                            Manufacturer = "Maserati"
                        },
                        new
                        {
                            Id = new Guid("76aebab7-5e11-49ff-a766-3df00130f6c2"),
                            EmployeeId = new Guid("8abcd94b-490d-4e5e-9c6e-4caeefd89d8c"),
                            Fuel = "Electric",
                            Manufacturer = "Porsche"
                        },
                        new
                        {
                            Id = new Guid("b39f687d-fce5-4551-90bd-d90fa2076e82"),
                            EmployeeId = new Guid("8abcd94b-490d-4e5e-9c6e-4caeefd89d8c"),
                            Fuel = "Gasoline",
                            Manufacturer = "BMW"
                        },
                        new
                        {
                            Id = new Guid("88b7786e-c5fb-490a-b4b8-20f43398972e"),
                            EmployeeId = new Guid("8abcd94b-490d-4e5e-9c6e-4caeefd89d8c"),
                            Fuel = "Electric",
                            Manufacturer = "BMW"
                        },
                        new
                        {
                            Id = new Guid("b8697d0d-f1e8-4caf-982e-ef0b36bafd0b"),
                            EmployeeId = new Guid("a58e9c9e-45a2-489e-88d2-4554b585dce1"),
                            Fuel = "Diesel",
                            Manufacturer = "Jaguar"
                        },
                        new
                        {
                            Id = new Guid("c50c2862-3d6e-4874-97af-3de6227f15a7"),
                            EmployeeId = new Guid("a58e9c9e-45a2-489e-88d2-4554b585dce1"),
                            Fuel = "Hybrid",
                            Manufacturer = "Land Rover"
                        },
                        new
                        {
                            Id = new Guid("71332782-1ecb-4c1a-889c-badb0be910a2"),
                            EmployeeId = new Guid("a58e9c9e-45a2-489e-88d2-4554b585dce1"),
                            Fuel = "Electric",
                            Manufacturer = "Toyota"
                        },
                        new
                        {
                            Id = new Guid("02472ac2-e5be-4b58-b020-cadcb3df4fcd"),
                            EmployeeId = new Guid("01df40e2-a098-462b-a42f-50a88ae8927f"),
                            Fuel = "Hybrid",
                            Manufacturer = "Hyundai"
                        },
                        new
                        {
                            Id = new Guid("38cd29d8-70ad-429d-bfad-e9f027616aa0"),
                            EmployeeId = new Guid("01df40e2-a098-462b-a42f-50a88ae8927f"),
                            Fuel = "Electric",
                            Manufacturer = "Cadillac"
                        },
                        new
                        {
                            Id = new Guid("54326028-31f7-426b-be1f-a40c6092f3b6"),
                            EmployeeId = new Guid("01df40e2-a098-462b-a42f-50a88ae8927f"),
                            Fuel = "Gasoline",
                            Manufacturer = "Fiat"
                        },
                        new
                        {
                            Id = new Guid("0393fcb8-8949-4643-81f5-a155de8318d7"),
                            EmployeeId = new Guid("38886041-4440-4f44-9177-acb509de7610"),
                            Fuel = "Hybrid",
                            Manufacturer = "Porsche"
                        },
                        new
                        {
                            Id = new Guid("cb35986c-b53d-48a4-ad5f-0dbead96deeb"),
                            EmployeeId = new Guid("38886041-4440-4f44-9177-acb509de7610"),
                            Fuel = "Diesel",
                            Manufacturer = "Volkswagen"
                        },
                        new
                        {
                            Id = new Guid("fc03210d-9322-4be5-bdfc-12c31733a706"),
                            EmployeeId = new Guid("38886041-4440-4f44-9177-acb509de7610"),
                            Fuel = "Diesel",
                            Manufacturer = "Maserati"
                        },
                        new
                        {
                            Id = new Guid("34ec95ff-bd85-4dcb-9d8a-885214b42658"),
                            EmployeeId = new Guid("b000ed0a-2921-4708-ad31-0cc0bd8766d6"),
                            Fuel = "Gasoline",
                            Manufacturer = "Nissan"
                        },
                        new
                        {
                            Id = new Guid("94142ea2-3e00-4a55-950e-76a4e7233661"),
                            EmployeeId = new Guid("b000ed0a-2921-4708-ad31-0cc0bd8766d6"),
                            Fuel = "Gasoline",
                            Manufacturer = "Dodge"
                        },
                        new
                        {
                            Id = new Guid("99b5ddf9-946e-434a-9c59-6a01e3bba937"),
                            EmployeeId = new Guid("b000ed0a-2921-4708-ad31-0cc0bd8766d6"),
                            Fuel = "Gasoline",
                            Manufacturer = "Bentley"
                        },
                        new
                        {
                            Id = new Guid("9aadb057-2f6c-43bd-99ee-77bc0ab232f0"),
                            EmployeeId = new Guid("1ce4c6f0-a08c-4bea-a7c6-0e5bbf43b6b8"),
                            Fuel = "Hybrid",
                            Manufacturer = "Mazda"
                        },
                        new
                        {
                            Id = new Guid("6e9523ae-81f8-4d91-a19c-2ffa21e71f67"),
                            EmployeeId = new Guid("1ce4c6f0-a08c-4bea-a7c6-0e5bbf43b6b8"),
                            Fuel = "Diesel",
                            Manufacturer = "Land Rover"
                        },
                        new
                        {
                            Id = new Guid("d2227cb4-2f68-4f89-b6fe-6771d70a5225"),
                            EmployeeId = new Guid("1ce4c6f0-a08c-4bea-a7c6-0e5bbf43b6b8"),
                            Fuel = "Diesel",
                            Manufacturer = "Hyundai"
                        },
                        new
                        {
                            Id = new Guid("48eb6671-c070-4d4a-a261-e32f89027b31"),
                            EmployeeId = new Guid("8fc9af11-7c57-4967-a18e-eaee2b57dfe7"),
                            Fuel = "Gasoline",
                            Manufacturer = "Porsche"
                        },
                        new
                        {
                            Id = new Guid("4134a7e1-550f-4516-9b62-e0a39238fa31"),
                            EmployeeId = new Guid("8fc9af11-7c57-4967-a18e-eaee2b57dfe7"),
                            Fuel = "Hybrid",
                            Manufacturer = "Volvo"
                        },
                        new
                        {
                            Id = new Guid("adbfd39a-3538-47ef-9e73-0de9fb970bb4"),
                            EmployeeId = new Guid("8fc9af11-7c57-4967-a18e-eaee2b57dfe7"),
                            Fuel = "Electric",
                            Manufacturer = "Audi"
                        },
                        new
                        {
                            Id = new Guid("67d44350-56ed-4a3c-b481-a01e45368535"),
                            EmployeeId = new Guid("dca79394-4910-4111-aba5-6b780a16b537"),
                            Fuel = "Electric",
                            Manufacturer = "Honda"
                        },
                        new
                        {
                            Id = new Guid("9fcb53a1-523e-4a20-96c4-60a66dfbc477"),
                            EmployeeId = new Guid("dca79394-4910-4111-aba5-6b780a16b537"),
                            Fuel = "Diesel",
                            Manufacturer = "Cadillac"
                        },
                        new
                        {
                            Id = new Guid("a66d700f-4637-4b31-9678-df8e0aa58a1d"),
                            EmployeeId = new Guid("dca79394-4910-4111-aba5-6b780a16b537"),
                            Fuel = "Gasoline",
                            Manufacturer = "Toyota"
                        },
                        new
                        {
                            Id = new Guid("d97fa1a3-cc99-485a-9074-c3e040e52973"),
                            EmployeeId = new Guid("e45cae6a-9067-4de6-b623-a0a05252ef56"),
                            Fuel = "Hybrid",
                            Manufacturer = "Ford"
                        },
                        new
                        {
                            Id = new Guid("83e68c03-48e8-40e9-b841-a86dbf6c6fcb"),
                            EmployeeId = new Guid("e45cae6a-9067-4de6-b623-a0a05252ef56"),
                            Fuel = "Gasoline",
                            Manufacturer = "Land Rover"
                        },
                        new
                        {
                            Id = new Guid("e2c1ef24-2635-49ff-a943-f535f4c39016"),
                            EmployeeId = new Guid("e45cae6a-9067-4de6-b623-a0a05252ef56"),
                            Fuel = "Electric",
                            Manufacturer = "Volvo"
                        });
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Vehicle", b =>
                {
                    b.HasOne("BogusNugetPackage.Models.Employee", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BogusNugetPackage.Models.Employee", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
