# Contacts API

@baseUrl = http://localhost:5000/api
### Choose the version of the API to test (v1 to v5)
@apiVersion = v4
### The id of the contact the repository starts with
@contactId = ffffffff-ffff-ffff-ffff-ffffffffffff

### Create a contact
POST {{baseUrl}}/{{apiVersion}}/contacts
Content-Type: application/json

{
  "email": "asmith@unknown.com"
}

### Create a contact with an invalid email address
POST {{baseUrl}}/{{apiVersion}}/contacts
Content-Type: application/json

{
  "email": "NOT_AN_EMAIL"
}

### Create another contact with an email that already exists
POST {{baseUrl}}/{{apiVersion}}/contacts
Content-Type: application/json

{
  "email": "jdoe@unknown.com"
}

### Get all contacts
GET {{baseUrl}}/{{apiVersion}}/contacts

### Get a contact by id
GET {{baseUrl}}/{{apiVersion}}/contacts/{{contactId}}

### Get a contact that doesn't exist
GET {{baseUrl}}/{{apiVersion}}/contacts/00000000-0000-0000-0000-000000000000
