@HowtoUseStringPoolApi_HostAddress = http://localhost:5225

GET {{HowtoUseStringPoolApi_HostAddress}}/home/
Accept: application/json
###

POST {{HowtoUseStringPoolApi_HostAddress}}/home/user
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/user/{name}
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/log
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/hostname
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/header
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/checktoken
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/encrypt/{text}
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/translate/{key}
Accept: application/json
###

GET {{HowtoUseStringPoolApi_HostAddress}}/home/validate/{email}
Accept: application/json
###