@baseUrl = http://localhost:5000/api
@jobId = babdbaa9-4276-4b35-a7e3-1723dc1c821c

### Create a new job 1
POST {{baseUrl}}/jobs/create-recurring-job-1

### Create a new job 2
POST {{baseUrl}}/jobs/create-recurring-job-2

### Create a new job 3
POST {{baseUrl}}/jobs/create-job-3

### Get job by id
GET {{baseUrl}}/jobs/{{jobId}}

### Get jobs statistics
GET {{baseUrl}}/jobs/statistics

