// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace EFCorePowerToolsExample.Data
{
    public partial interface IDBContextProcedures
    {
        Task<int> CountBooksInCategory_SPAsync(int? CategoryID, OutputParameter<int?> BookCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
