// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using EFCorePowerToolsExample.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace EFCorePowerToolsExample.Data
{
    public partial interface IDBContextProcedures
    {
        Task<int> CountBooksInCategory_SPAsync(int? CategoryID, OutputParameter<int?> BookCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
