@baseUrl = http://localhost:5000

GET {{baseUrl}}/api/events/1

###

POST {{baseUrl}}/api/events/1/reservations
Content-Type: application/json

{ "quantity": 3 }

###

POST {{baseUrl}}/api/events/2/reservations
Content-Type: application/json

{ "quantity": 3 }

###

POST {{baseUrl}}/api/events/1/reservations
Content-Type: application/json

{ "quantity": 0 }

###

GET {{baseUrl}}/api/events/99
