<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Files\text-file.txt" />
    <EmbeddedResource Include="Resources\Pdf\pdf-file.pdf" />
    <EmbeddedResource Include="Resources\text-file.txt" />
    <EmbeddedResource Include="my-folder\note.txt" />
	<EmbeddedResource Include="..\Embedded_Resources_in_NET.sln" />
	<EmbeddedResource Include="..\..\README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Embedded_Resources_in_NET_Library\Embedded_Resources_in_NET_Library.csproj" />
  </ItemGroup>

</Project>
