<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <Configuration>Release</Configuration>
    <IsPackable>false</IsPackable>
  </PropertyGroup>    
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>    
  <ItemGroup>
    <ProjectReference Include="..\JsonDeserializationDynamicObject\JsonDeserializationDynamicObject.csproj" />
  </ItemGroup>    
  <ItemGroup>
    <None Update="MovieStats.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>  
</Project>
