// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"experience_level")]
            public string Experience_level { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"employment_type")]
            public string Employment_type { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"job_title")]
            public string Job_title { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"salary_in_usd")]
            public float Salary_in_usd { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"remote_ratio")]
            public float Remote_ratio { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"company_size")]
            public string Company_size { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"experience_level")]
            public float[] Experience_level { get; set; }

            [ColumnName(@"employment_type")]
            public float[] Employment_type { get; set; }

            [ColumnName(@"job_title")]
            public float[] Job_title { get; set; }

            [ColumnName(@"salary_in_usd")]
            public float Salary_in_usd { get; set; }

            [ColumnName(@"remote_ratio")]
            public float Remote_ratio { get; set; }

            [ColumnName(@"company_size")]
            public float[] Company_size { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
