
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Experience_level = @"SE",
    Employment_type = @"FT",
    Job_title = @"Business Intelligence Engineer",
    Remote_ratio = 0F,
    Company_size = @"L",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary_in_usd with predicted Salary_in_usd from sample data...\n\n");


Console.WriteLine($"Experience_level: {@"SE"}");
Console.WriteLine($"Employment_type: {@"FT"}");
Console.WriteLine($"Job_title: {@"Business Intelligence Engineer"}");
Console.WriteLine($"Salary_in_usd: {104300F}");
Console.WriteLine($"Remote_ratio: {0F}");
Console.WriteLine($"Company_size: {@"L"}");


var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary_in_usd: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

