// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
namespace SampleClassification.ConsoleApp
{
    public partial class SampleClassification
    {
        /// <summary>
        /// model input class for SampleClassification.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"checking_status")]
            public string Checking_status { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"duration")]
            public float Duration { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"credit_history")]
            public string Credit_history { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"purpose")]
            public string Purpose { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"credit_amount")]
            public float Credit_amount { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"savings_status")]
            public string Savings_status { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"employment")]
            public string Employment { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"installment_commitment")]
            public float Installment_commitment { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"personal_status")]
            public string Personal_status { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"other_parties")]
            public string Other_parties { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"residence_since")]
            public float Residence_since { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"property_magnitude")]
            public string Property_magnitude { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"age")]
            public float Age { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"other_payment_plans")]
            public string Other_payment_plans { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"housing")]
            public string Housing { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"existing_credits")]
            public float Existing_credits { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"job")]
            public string Job { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"num_dependents")]
            public float Num_dependents { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"own_telephone")]
            public string Own_telephone { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"foreign_worker")]
            public bool Foreign_worker { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"class")]
            public string Class { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SampleClassification.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"checking_status")]
            public float[] Checking_status { get; set; }

            [ColumnName(@"duration")]
            public float Duration { get; set; }

            [ColumnName(@"credit_history")]
            public float[] Credit_history { get; set; }

            [ColumnName(@"purpose")]
            public float[] Purpose { get; set; }

            [ColumnName(@"credit_amount")]
            public float Credit_amount { get; set; }

            [ColumnName(@"savings_status")]
            public float[] Savings_status { get; set; }

            [ColumnName(@"employment")]
            public float[] Employment { get; set; }

            [ColumnName(@"installment_commitment")]
            public float Installment_commitment { get; set; }

            [ColumnName(@"personal_status")]
            public float[] Personal_status { get; set; }

            [ColumnName(@"other_parties")]
            public float[] Other_parties { get; set; }

            [ColumnName(@"residence_since")]
            public float Residence_since { get; set; }

            [ColumnName(@"property_magnitude")]
            public float[] Property_magnitude { get; set; }

            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"other_payment_plans")]
            public float[] Other_payment_plans { get; set; }

            [ColumnName(@"housing")]
            public float[] Housing { get; set; }

            [ColumnName(@"existing_credits")]
            public float Existing_credits { get; set; }

            [ColumnName(@"job")]
            public float[] Job { get; set; }

            [ColumnName(@"num_dependents")]
            public float Num_dependents { get; set; }

            [ColumnName(@"own_telephone")]
            public float[] Own_telephone { get; set; }

            [ColumnName(@"foreign_worker")]
            public float[] Foreign_worker { get; set; }

            [ColumnName(@"class")]
            public uint Class { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath(@"SampleClassification\SampleClassification.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("class");
            if (labelColumn == null)
            {
                throw new Exception("class column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}