global using System.ComponentModel.DataAnnotations;
global using UsingResultPatternInNETWebAPI.Domain;
global using UsingResultPatternInNETWebAPI.Dtos;
global using UsingResultPatternInNETWebAPI.Exceptions;
global using UsingResultPatternInNETWebAPI.Repositories;
global using UsingResultPatternInNETWebAPI.Services;
