using ReadingAppsettingsInConsoleApplication.Configurations.ConfigurationProviders;

namespace ReadingAppsettingsInConsoleApplicationTests;

public class RetrievalConfigurationWithGenericMethodTests() : TestBase(new RetrievalConfigurationWithGenericMethod())
{
}