// <auto-generated />
using GraphQLStrawberryShake.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLStrawberryShake.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240228102207_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("GraphQLStrawberryShake.Server.ShippingContainer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShippingContainers");
                });

            modelBuilder.Entity("GraphQLStrawberryShake.Server.ShippingContainer", b =>
                {
                    b.OwnsOne("GraphQLStrawberryShake.Server.ShippingContainer+AvailableSpace", "Space", b1 =>
                        {
                            b1.Property<string>("ShippingContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Height")
                                .HasColumnType("REAL");

                            b1.Property<double>("Length")
                                .HasColumnType("REAL");

                            b1.Property<double>("Width")
                                .HasColumnType("REAL");

                            b1.HasKey("ShippingContainerId");

                            b1.ToTable("ShippingContainers");

                            b1.WithOwner()
                                .HasForeignKey("ShippingContainerId");
                        });

                    b.Navigation("Space")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
